name: dartbrcode
version: 1.0.0
description: Dart wrapper for Rust BrCode
repository: https://github.com/naomijub/brcode
sdk: ">=1.8.0 <2.0.0"
dependencies:
  ffi: ^0.1.3
dev_dependencies:
  test: ^1.15.3