name: dartbrcode
version: 0.3.0
description: Dart wrapper for Rust BrCode
repository: https://github.com/naomijub/brcode
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  ffi: ^0.1.3
dev_dependencies:
  test: ^1.15.3